name: Prod build and deployment
on:
  push:
    branches:
      - 'main'
jobs:
  CheckReleaseManager:
    runs-on: ubuntu-latest
    steps:
      - name: Check Release Manager
        id: release_manager_check
        run: |
          if [ "${{ github.actor }}" != "AsyaSto" ]; then
            echo "This workflow was triggered by someone other than the release manager. Aborting..."
            exit 1
          fi
  BuildSimulation:
    runs-on: ubuntu-latest
    needs: CheckReleaseManager
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          echo building and packing an app...
  DeploySimulation:
    runs-on: ubuntu-latest
    needs: BuildSimulation
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo deploying into Test env
